bag/urls.py
"""
Python imported modules
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

foot_connect/urls.py
"""
Python imported modules
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('sendemail/', include('sendemail.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path(
        'delete/<int:product_id>/',
        views.delete_product, name='delete_product'),
    path(
        'product/<int:product_id>/add-comment',
        views.add_comment, name='add-comment'),
    path(
        'product/<int:product_id>/delete-comment',
        views.delete_comment, name='delete-comment'),
]

checkout/models.py
"""
Python imported modules
"""
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):

    """
    Product order model
    """
    order_number = models.CharField(
        max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='orders')
    full_name = models.CharField(
        max_length=50, null=False, blank=False)
    email = models.EmailField(
        max_length=254, null=False, blank=False)
    phone_number = models.CharField(
        max_length=20, null=False, blank=False)
    country = CountryField(
        blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(
        max_length=20, null=True, blank=True)
    town_or_city = models.CharField(
        max_length=40, null=False, blank=False)
    street_address1 = models.CharField(
        max_length=80, null=False, blank=False)
    street_address2 = models.CharField(
        max_length=80, null=True, blank=True)
    county = models.CharField(
        max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(
        null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = \
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):

    """
    Quantity
    """
    order = models.ForeignKey(
        Order, null=False, blank=False,
        on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False,
        on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2, null=True, blank=True)  # XS, S, M, L, XL uk 7, 8, 9, 10, 11
    quantity = models.IntegerField(
        null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2,
        null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
""" import models """
from django.db import models
from datetime import datetime


class Category(models.Model):
    """ Category models """

    class Meta:
        """ Metadata """
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        """ get_friendly_name function """
        return self.friendly_name


class Product(models.Model):

    """ Product model """

    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    gender = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(
        default=False, null=True, blank=True)
    """ Custom model field """
    shoe_sizes = models.BooleanField(
        default=False, null=True, blank=True)
    price = models.DecimalField(
        max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class Comment(models.Model):

    """ Custom model that allows users to
    leave reviews on products  """

    product = models.ForeignKey(
        Product, related_name="comments", on_delete=models.CASCADE)
    comment_name = models.CharField(max_length=254)
    comment_title = models.CharField(max_length=254)
    comment_body = models.TextField()
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.product.name, self.comment_name)

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category, Comment


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('comment_title', 'comment_body')
        widgets = {
            'comment_body': forms.Textarea(attrs={'class': 'form-control'}),
            'comment_title': forms.Textarea(attrs={'class': 'form-control'}),
        }

products/views.py
""" imports """
from django.shortcuts import (
    render, redirect, reverse, get_object_or_404)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category, Comment
from .forms import ProductForm, CommentForm


def all_products(request):
    """
    A view to show all products, including sorting and search queries
    """
    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):

    """
    A view to show individual product details
    """
    product = get_object_or_404(Product, pk=product_id)

    num_comments = Comment.objects.filter(product=product).count()

    context = {
        'product': product,
        'num_comments': num_comments,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):

    """
    Add a product to the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):

    """
    Edit a product in the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete a product from the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))


@login_required
def add_comment(request, product_id):
    """
    Add comments
    """
    product = get_object_or_404(Product, pk=product_id)

    form = CommentForm(instance=product)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=product)
        if form.is_valid():
            name = request.user.username
            title = form.cleaned_data['comment_title']
            body = form.cleaned_data['comment_body']
            c = Comment(product=product,
                        comment_name=name,
                        comment_title=title,
                        comment_body=body)
            c.save()
            messages.success(request, 'Comment added successfully!')
            return redirect('products')
        else:
            messages.error(request, 'Sorry, comment not sent')
    else:
        form = CommentForm()

    template = "products/add_comment.html"
    context = {
        'form': form,
    }
    return render(request, template, context)


@login_required
def delete_comment(request, product_id):
    """
    Delete comments
    """
    comment = Comment.objects.filter(product=product_id).last()
    product_id = comment.product.id
    comment.delete()
    messages.success(request, 'Successfully deleted! comment')
    return redirect(reverse('products'))

products/templates/products/add_comment.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="max-width mx-auto">
        <form class="contact-form container col-12 input-border" method="POST">
            <fieldset>
                {% csrf_token %}
                <h2 class="text-center font-weight-bold comment_header">Leave Us a Review</h2>
                <hr>
                <p class="text-center">Share your thoughts with us! <a href="{% url 'home' %}">Home</a></p>
                <!-- Review Title -->
                <div class="col-lg-12 col-sm-12 col-xs-12 ">
                    <label for="comment_title">Add a title</label>
                    <input type="text" name="comment_title" class="form-control" id="comment_title"
                        placeholder="Write here.." required />
                </div>

                <div class="col-lg-12 col-sm-12 col-xs-12  form-actions">
                    <label for="comment_body">Add a review</label>
                    <textarea rows="6" name="comment_body" class="form-control" id="comment_body"
                        placeholder="Comment here.." required></textarea>

                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button id="submit" class="btn btn-info rounded-0 mt-3" type="submit">Send Comment</button>
                </div>
            </fieldset>
        </form>

    </div>
</div>
{% endblock %}

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="text-center mb-4 title-font">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid mt-4">
        <div class="row">
            <div class="col-12 col-md-6 mt-4 col-lg-4 offset-lg-2">
                <div class="image-container title-font">
                    {% if product.image %}
                        <a href="{{ product.image.url }}" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                        {% else %}
                        <a href="{{ MEDIA_URL }}noimage.png" target="_blank">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4">
                <div class="product-details-container mb-5 mt-md-5">
                    <p class="mb-0">{{ product.name }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">£{{ product.price }}</p>
                    {% if product.category %}
                    <p class="small mt-1 mb-0">
                        <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                            <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                        </a>
                    </p>
                    {% endif %}
                    {% if product.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}

                    {% if request.user.is_superuser %}
                        <small class="ml-3">
                            <a href="{% url 'edit_product' product.id %}">Edit</a>
                            <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                        </small>
                    {% endif %}

                    <p class="mt-3">{{ product.description }}</p>
                    <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% if product.shoe_sizes %}
                            <!-- Footwear size -->
                            <div class="col-12">
                                <p><strong>Size:</strong></p>
                                <select class="form-control rounded-0 w-50 mobile-width-100" name="product_size" id='id_product_size'>
                                    <option value="7"> uk 7</option>
                                    <option value="8">uk 8</option>
                                    <option value="9" selected>uk 9</option>
                                    <option value="10">uk 10</option>
                                    <option value="11">uk 11</option>
                                </select>
                            </div>
                            {% endif %}
                            {% if product.has_sizes %}
                             <!-- Clothing Size-->
                            <div class="col-12">
                                <p><strong>Size:</strong></p>
                                <select class="form-control rounded-0 w-50 mobile-width-100" name="product_size" id='id_product_size'>
                                    <option value="xs">XS</option>
                                    <option value="s">S</option>
                                    <option value="m" selected>M</option>
                                    <option value="l">L</option>
                                    <option value="xl">XL</option>
                                </select>
                            </div>
                            {% endif %}
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50 mobile-width-100">
                                    <div class="input-group input-group-{{ product.id }}">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-0 decrement-qty_{{ product.id }}" 
                                                data-item_id="{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control qty_input id_qty_{{ product.id }}" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ product.id }}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-0 increment-qty_{{ product.id }}"
                                                data-item_id="{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col{% if s %}-12 mt-2{% endif %}">
                                <a href="{% url 'products' %}" class="btn btn-mobile btn-outline-black rounded-0 w-50">
                                    
                                    <span class="text-uppercase text-center">Keep Shopping</span>
                                </a>
                                <input type="submit" class="btn btn-black btn-mobile rounded-0 text-uppercase w-50 mt-3" value="Add to Bag">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                         
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Product Comments and Review Section -->
    <div id="accordion" class="container comments">
        <div class="card">
            <div class="card-header" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true"
                aria-controls="collapseOne" id="headingOne">
                <div class="mb-0">
                    <button class="btn text-left">
                        Reviews ({{ num_comments }})
                            <small><i class="fas fa-star mr-1"></i></small>
                            <small><i class="fas fa-star mr-1"></i></small>
                            <small><i class="fas fa-star mr-1"></i></small>
                            <small><i class="fas fa-star mr-1"></i></small>
                            <small><i class="fas fa-star mr-1"></i></small>
                        
                    </button>
                </div>
            </div>

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    <div class="col col-lg-6">
                        <br>
                        {% if not product.comments.all %}

                        <p>No comments added yet...</p>
                        <p><a class="btn btn-primary" href="{% url 'add-comment' product.id %}">  Add Comment </a></p>

                        {% else %}

                        {% for comment in product.comments.all %}

                        <p><strong>{{ comment.comment_name }}</strong> - {{ comment.date_added }}</p>
                        <p><strong>{{ comment.comment_title }}</strong></p>
                        <p>{{ comment.comment_body }}</p>
                     
                       
                        {% if request.user.username == comment.comment_name %}
                        <div class="row mb-2">
                            <div class="col col-lg-4 col-sm-6">
                                <a class="btn btn-info" href="{% url 'add-comment' product.id %}"> Add Comment</a>
                            </div>
                            <div class="col col-lg-4 col-sm-6">
                                <a class="btn btn-danger" href="{% url 'delete-comment' product.id %}"> Delete Comment </a>  
                            </div>
                        </div>
                        <hr>
                        {% endif %}

                        {% endfor %}

                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
                aria-controls="collapseOne" id="headingTwo">
                <div class="mb-0">
                    <button class="btn text-left">
                        Product Description
                    </button>
                </div>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                <div class="card-body mt-2">
                    <div class="col col-lg-6">
                       <p>{{ product.description }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" data-toggle="collapse" data-target="#collapseThree"
            aria-expanded="false" aria-controls="collapseThree" id="headingThree">
                <div class="mb-0">
                    <button class="btn text-left">
                        Delivery Information
                    </button>
                </div>
            </div>
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                <div class="card-body mt-4">
                    <div class="col col-lg-6">
                        <h5><strong> Standard Delivery</strong> - £4.50</h5>
                        <p>Receive within 2 - 4 working days (Excludes bank holidays).
                        Includes door to door tracking.
                        Free with all orders over £49.</p>

                        <h5><strong> Track My Order</strong></h5>
                        <p>You can track your order via the link 
                        included in your dispatch email 
                        (make sure you double-check this 
                        hasn't ended up in your junk folder).
                        Not received a dispatch email?
                        The below might help:
                        Orders placed before 11pm Monday - 
                        Thursday using our Next Day Delivery 
                        service can arrive at any time up to 8pm the following day.
                        Orders placed after 11pm Thursday, 
                        Friday and Saturday will be dispatched on Sunday.
                        Standard Delivery can take up to 4 working days.</p> 
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}